### ISSUE TITLE
Need more configurability of generated reports

### ISSUE THREAD

**Issue by vraravam** [jeremylong/dependency-check-gradle#1]
I would like to be able to configure report outputs (both directory as well as filename itself). Please look at the reports closure as an example here: https://docs.gradle.org/current/dsl/org.gradle.api.reporting.Reporting.html. Till this is fixed, I will have to use https://github.com/danielsomerfield/gradle-cve-dependency-check/

My usage is that I include the plugin into all my root + subprojects (similar to what you have put in the README), but I need to also collect all the reports generated into a single test_artifacts directory to be exposed by the CI tool. For this scenario, I am forced to copy from each subproject into the final test_artifacts folder one-by-one. Instead, if the generation were to be configurable, I could set the output like this:
```
reports {
    html.destination = rootProject.file("test_artifacts/security-reports-${project.name}")
}
```

**Comment by jeremylong** [comment]
I really like your suggestion; I'll work on adding this. However, you might be able to achieve similar results with the current release by configuring the `reportsDirName`. Non-intuitive and not documented - but this allows renaming the file.

```groovy
dependencyCheck {
	reportsDirName = "test_artifacts/security-reports-${project.name}.html"
}
```

However, this would still put the file in the sub projects build directory.

It shouldn't take me long to implement the gradle reporting api.

**Comment by vraravam** [comment]
Thanks - looking forward to using the *new and improved* version soon :)

**Comment by vraravam** [comment]
yup - can confirm that the 'build' folder is hard-coded. Is there an ETA for getting this implemented?

**Comment by vraravam** [comment]
ping - sorry, but i'm stuck without this. Is it possible for you to publish a quick fix?

**Comment by jeremylong** [comment]
Sorry about the delay - life got in the way. Luckily I'm home sick today and had a chance to look at this. I have one small change to make to the core dependency-check project and I should be able to release 1.3.3 within a day or two.

I just commited the rest of the gradle plugin's source (mistake in the gitignore and I didn't realize the code never got uploaded). I changed `reportsDirName` to `outputDirectory`. It defaults to "build/reports"; however, you can fully change this to a file path (as long as your output format is not ALL). The following would work in 1.3.3:

```groovy
dependencyCheck {
	skipTestGroups=false
	outputDirectory=rootProject.file("test_artifacts/security-reports-${project.name}.html")
}
```

**Comment by jeremylong** [comment]
1.3.3 has been released. However, I am leaving this ticket open until the reporting API has been implemented.

**Comment by vraravam** [comment]
Tx - im unblocked for now - except for issue #2 which I will comment out for the time being so that I can get this tool incorporated into all my projects.
