### ISSUE TITLE
org/owasp/dependencycheck/gradle/DependencyCheck : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by martosoler** [jeremylong/dependency-check-gradle#10]
Hi,

I'm trying to use the plugin but I'm getting:
`org/owasp/dependencycheck/gradle/DependencyCheck : Unsupported major.minor version 52.0`
The issue is happening with both 1.3.6 and 1.4.0 versions.
Are you compiling with Java 8?
Thanks

**Comment by jeremylong** [comment]
The gradle plugin was compiled using:
```
Groovy:       2.4.4
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
```

For the next version I will set the `targetCompatibility` to 1.7.
