### ISSUE TITLE
3.3.2 is no longer hosted on Maven Central

### ISSUE THREAD

**Issue by quinnjn** [jeremylong/dependency-check-gradle#101]
Tried to follow your install instructions and the plugin could not be found. After debugging it via [mvnrepository](https://mvnrepository.com/artifact/org.owasp/dependency-check-gradle/3.3.2), I found that 3.3.1 was the last version upload to `mavenCentral`.  Version 3.3.2 is available on [plugins.gradle.org](https://plugins.gradle.org/m2/org/owasp/dependency-check-gradle/3.3.2/).

Unsure if it was intentional to switch repositories but if so, the README needs an update to include this repository instead of `mavenCentral()`.

Otherwise we'll wait for your 3.3.2 version to show up on `mavenCentral()`

**Comment by jeremylong** [comment]
Sorry about that - it should be in Central shortly. It was pushed to central, the staging repository was closed, and then I got distracted and never hit the release button.
