### ISSUE TITLE
Android test dependencies are not ignored

### ISSUE THREAD

**Issue by imbeyondboredom** [jeremylong/dependency-check-gradle#11]
When using this library with Android, none of the Android test dependencies are ignored.

I've added some code [here](https://github.com/imbeyondboredom/dependency-check-gradle/commit/594603002761685e3a1dfc5481a98efd7fc6eae0) for a PR but whenever I run the command
`./gradlew build install integTest --info`
the test still fails. 

So this is both a bug report as well as my asking: 
It seems like my changes aren't taking effect, am I running the tests in a way that wont get my changes?

**Comment by imbeyondboredom** [comment]
More details. I finally got this debugging. It turns out that the Android plugin generates a number of other configurations based on your flavors and builds that have test dependencies but don't match the patterns contained in this lib.

In addition to the "androidTest.." configuration, the plugin creates configurations that end in "testapk" that also have the test dependencies.

Instead of adding all of these possibilities to this plugin, I think I'm going to create a PR that allows users to create skip configurations by wildcard.

This would be easiest if I allow the user to specify a regex.. but then a user could create an infinite loop regex and DOS a build server. Is that an acceptable risk? If not then I'll have to write some wildcard code as I can't find a java framework class that just does that

**Comment by bodewig** [comment]
I think the - already merged #8 - should work for you. It doesn't use a regex but rather a spelled out list of configurations but you can probably easily identify those configurations relevant to you and use `scanConfigurations`

**Comment by jeremylong** [comment]
we could update the `scanConfigurations` to allow regex.

**Comment by bodewig** [comment]
True. The easiest way probably would be to treat the list elements of `scanConfigurations` (and `skipConfigurations`) as regexes and match against them rather than using a `contains` check. @jeremylong do you want me to give it a try?

**Comment by tristan-perryman** [comment]
I was also just having  the same problem as mentioned in this issue. My thought was to just skip any configuration that has the word "test" in it. The advantage of that would be then things would "just work" (at least for now) and no one would have to mess around with skipConfigurations. 

That said, maybe both changes are useful?

**Comment by imbeyondboredom** [comment]
I figured that checking for test might be too broad. My main reason for arguing for regex/wildcard matching is that on android if you add a new flavor it adds a few test configurations that you have to manually ignore. It would be much easier to specify a wildcard so we can use the same configuration across projects. 

I went the route of choosing wildcards instead of regex because you could potentially DOS a server using a malformed regex and the thought of the vulnerability scanner having a vulnerability like that seemed wrong. That being said... if you have access to the sourcecode and the ability to run builds then this seems like a trivial problem.. so if you guys are ok with allowing full regex then I'm OK with it too.

[Here](https://github.com/imbeyondboredom/dependency-check-gradle/commit/a88973627d566a9d4e622a0a76449424e86f16e0) is the start of me adding wildcard matching. When I use this on my project everything seems to work but I can't get the integration tests to run for the life of me. I'll try to get those running when I can. Do you all have problems running the integration tests?

**Comment by jeremylong** [comment]
I think a regex solution to this problem as it allows a bit more flexibility. This likely won't make the 1.4.3 release as that has some important updates that need to get pushed but I will circle back after 1.4.3 is released and enhance the gradle plugin to handle regexes to skip/scan specific configurations.

**Comment by stefanneuhaus** [comment]
A (regex) solution for configuration excludes is highly appreciated!

I also just observed that there is already undocumented _non-regex_ support via the [skipConfigurations](https://github.com/jeremylong/dependency-check-gradle/blob/master/src/main/groovy/org/owasp/dependencycheck/gradle/extension/CheckExtension.groovy#L89) configuration property. IMHO this is very helpful and should still be documented until the full-featured regex solution is in place.

**Comment by jeremylong** [comment]
The documentation has been updated and will be published with the next release.

**Comment by stefanneuhaus** [comment]
I thing the fix that I proposed for the issue ["Test configuration detection is broken"](https://github.com/jeremylong/dependency-check-gradle/issues/17) (see [PR](https://github.com/jeremylong/dependency-check-gradle/pull/18/commits/988dc40c15926818654990436889cb819ca0242d#diff-ca95dd51a667d486220feef1effffedf)) could be easily extended to cover this issue as well. I would suggest to not only rely on the name of configuration in question, but instead analyze its whole configuration hierarchy.

The suggestion is to call a configuration a test configuration, iff any of the following conditions holds:
- the configuration name starts with `test`
- the configuration name starts with `androidTest`
- the name of any of its parent configurations equals `testCompile`
- the name of any of its parent configurations equals `androidTestCompile`

I tested the approach with the configurations of an Android project with any of the following plugins: `android`, `com.android.application`, `kotlin-android`, `kotlin-android-extensions`. Depending on the actual plugin used there configurations and their hierarchies differ. But nevertheless the logic seems to fit and does not produce false positives.

The actual configurations (and hierarchies) and the detected test configuration flags are (all plugins together):
```
_debugAndroidTestApk --> androidTestApk --> androidTestCompile: TRUE
_debugAndroidTestApk --> androidTestCompile --> androidTestApk: TRUE
_debugAndroidTestCompile --> androidTestCompile --> androidTestProvided: TRUE
_debugAndroidTestCompile --> androidTestProvided --> androidTestCompile: TRUE
_debugApk --> compile --> apk --> debugApk --> debugCompile: FALSE
_debugApk --> compile --> debugApk --> apk --> debugCompile: FALSE
_debugApk --> compile --> debugCompile --> debugApk --> apk: FALSE
_debugApk --> debugCompile --> apk --> compile --> debugApk: FALSE
_debugCompile --> compile --> provided --> debugProvided --> debugCompile: FALSE
_debugCompile --> debugCompile --> compile --> provided --> debugProvided: FALSE
_debugCompile --> debugProvided --> compile --> provided --> debugCompile: FALSE
_debugCompile --> provided --> compile --> debugCompile --> debugProvided: FALSE
_debugUnitTestApk --> testApk --> testDebugApk --> testDebugCompile --> testCompile: TRUE
_debugUnitTestApk --> testDebugApk --> testApk --> testDebugCompile --> testCompile: TRUE
_debugUnitTestApk --> testDebugCompile --> testApk --> testDebugApk --> testCompile: TRUE
_debugUnitTestApk --> testDebugCompile --> testDebugApk --> testCompile --> testApk: TRUE
_debugUnitTestCompile --> testDebugCompile --> testCompile --> testDebugProvided --> testProvided: TRUE
_debugUnitTestCompile --> testDebugCompile --> testProvided --> testDebugProvided --> testCompile: TRUE
_debugUnitTestCompile --> testDebugProvided --> testProvided --> testDebugCompile --> testCompile: TRUE
_debugUnitTestCompile --> testProvided --> testDebugCompile --> testDebugProvided --> testCompile: TRUE
_releaseApk --> compile --> apk --> releaseCompile --> releaseApk: FALSE
_releaseApk --> compile --> releaseCompile --> releaseApk --> apk: FALSE
_releaseApk --> releaseApk --> releaseCompile --> compile --> apk: FALSE
_releaseApk --> releaseCompile --> releaseApk --> apk --> compile: FALSE
_releaseCompile --> compile --> releaseProvided --> provided --> releaseCompile: FALSE
_releaseCompile --> provided --> compile --> releaseProvided --> releaseCompile: FALSE
_releaseCompile --> releaseProvided --> releaseCompile --> compile --> provided: FALSE
_releaseUnitTestApk --> testApk --> testReleaseApk --> testReleaseCompile --> testCompile: TRUE
_releaseUnitTestApk --> testReleaseApk --> testCompile --> testReleaseCompile --> testApk: TRUE
_releaseUnitTestApk --> testReleaseApk --> testReleaseCompile --> testApk --> testCompile: TRUE
_releaseUnitTestApk --> testReleaseCompile --> testApk --> testReleaseApk --> testCompile: TRUE
_releaseUnitTestCompile --> testCompile --> testReleaseCompile --> testProvided --> testReleaseProvided: TRUE
_releaseUnitTestCompile --> testProvided --> testReleaseProvided --> testReleaseCompile --> testCompile: TRUE
_releaseUnitTestCompile --> testReleaseCompile --> testProvided --> testCompile --> testReleaseProvided: TRUE
_releaseUnitTestCompile --> testReleaseProvided --> testProvided --> testReleaseCompile --> testCompile: TRUE
androidJacocoAgent: FALSE
androidJacocoAnt: FALSE
androidTestApk: TRUE
androidTestCompile: TRUE
androidTestProvided: TRUE
androidTestWearApp: TRUE
apk: FALSE
archives: FALSE
compile: FALSE
debugApk: FALSE
debugCompile: FALSE
debugProvided: FALSE
debugWearApp: FALSE
default: FALSE
default-mapping: FALSE
default-metadata: FALSE
kapt: FALSE
kaptAndroidTest: FALSE
kaptDebug: FALSE
kaptRelease: FALSE
kaptTest: FALSE
kaptTestDebug: FALSE
kaptTestRelease: FALSE
provided: FALSE
releaseApk: FALSE
releaseCompile: FALSE
releaseProvided: FALSE
releaseWearApp: FALSE
testApk: TRUE
testCompile: TRUE
testDebugApk: TRUE
testDebugCompile: TRUE
testDebugProvided: TRUE
testDebugWearApp: TRUE
testProvided: TRUE
testReleaseApk: TRUE
testReleaseCompile: TRUE
testReleaseProvided: TRUE
testReleaseWearApp: TRUE
testWearApp: TRUE
wearApp: FALSE
```

With any plugin used it also detected the flavor-specific test configurations:
```
_debugAndroidTestApk
_debugAndroidTestCompile
_debugUnitTestApk
_debugUnitTestCompile
_releaseUnitTestApk
_releaseUnitTestCompile
```

If this is acceptable, I can provide a PR.

**Comment by imbeyondboredom** [comment]
That sounds like it makes sense to me. I'm still very interested in this as I'm currently in charge of implementing this across a large number of android projects so if I can help let me know

**Comment by stefanneuhaus** [comment]
@imbeyondboredom Thanks for your feedback! I think at the moment there is not much you can help with. I am waiting for feedback from @jeremylong, before I make the effort to provide a PR with proper test coverage.

@imbeyondboredom If you are uncertain and want to have a try, I could provide a built version for testing (to be installed via a [Flat directory repository](https://docs.gradle.org/current/userguide/dependency_management.html#sec:flat_dir_resolver)).

**Comment by stefanneuhaus** [comment]
What is the exact scope of this issue? Was is about respecting the Android test dependencies (which has been fixed with PR #18 for issue #17) or is there still need for the regex support?

**Comment by imbeyondboredom** [comment]
This was originally for Android test dependencies. I'm not familiar with the full gradle landscape though so if there's the possibility that other plugins might add other gradle test flavors like "chromeTestCompile"? But in terms of what I need PR #18 solves for that!

**Comment by stefanneuhaus** [comment]
There is certainly the possibility that other plugins introduce test configurations that are not detected by our logic. But still there is the possibility to exclude them via ```skipConfigurations```.

@jeremylong I'd suggest to either
* define the requirements for a regex/wildcard solution (preferably in a new issue)
* just close this one as the immediate issue is solved.

**Comment by jeremylong** [comment]
@stefanneuhaus thanks for you help making the plugin better.  I think adding a regular expression to the `skipConfigurations` and `scanConfigurations` would be beneficial - but likely not a priority.  I'll open a new ticket.
