### ISSUE TITLE
current version 4.0.2 not available on MavenCentral and JCenter

### ISSUE THREAD

**Issue by stefanneuhaus** [jeremylong/dependency-check-gradle#114]
The current version 4.0.2 is not available on [MavenCentral](https://search.maven.org/search?q=a:dependency-check-gradle) and [JCenter](https://bintray.com/bintray/jcenter/org.owasp%3Adependency-check-gradle/). Though it is still available in the [Gradle Plugin Portal](https://plugins.gradle.org/plugin/org.owasp.dependencycheck).

**Comment by jeremylong** [comment]
not sure how that was missed - I just pushed 4.0.2 to central.  Note, the 4.x branch increased the FP rate significantly and I don't recommend using it. I'm hoping to have a 5.0.0 release ready soon which should resolve some of the issues introduced in the 4.x release.

**Comment by jeremylong** [comment]
4.0.2 isn't in the search yet - give it another hour.  But the plugin  can be found here: https://repo1.maven.org/maven2/org/owasp/dependency-check-gradle/4.0.2/
