### ISSUE TITLE
Document scanConfigurations and skipConfigurations

### ISSUE THREAD

**Issue by brianpreuss** [jeremylong/dependency-check-gradle#12]
Hi,

by looking at the source code from CheckExtension.groovy I found the configurations scanConfigurations and skipConfigurations which are not documented (only GroovyDoc).

Regards,

Brian

**Comment by bodewig** [comment]
I intended to provide documentation but couldn't find the source to prepare a patch, sorry.

**Comment by jeremylong** [comment]
The documentation is located in [DependencyCheck/src/site/markdown/dependency-check-gradle](https://github.com/jeremylong/DependencyCheck/tree/master/src/site/markdown/dependency-check-gradle). I located it there as it is easier to maintain a single gh-pages for the entire ODC project.

**Comment by bodewig** [comment]
filed https://github.com/jeremylong/DependencyCheck/pull/542

**Comment by jeremylong** [comment]
Thanks for the PR @bodewig.
