### ISSUE TITLE
how to make jobs fail after ran dependencyCheckPublisher stage

### ISSUE THREAD

**Issue by llsJllsJ** [jeremylong/dependency-check-gradle#121]
Hi,

Is there any way to make jobs fail piority to discontinue other stages in pipeline?
As I tried I will run all left stages and mark fails job at last.

Thanks

**Comment by jeremylong** [comment]
This appears to be a question about the Jenkins plugin - not the gradle plugin.  I believe there is a configuration option in the settings - fail on CVSS score that should cause the build to fail. However, I do not use the Jenkins plugin myself.
