### ISSUE TITLE
Support for database server

### ISSUE THREAD

**Issue by szpak** [jeremylong/dependency-check-gradle#122]
It would be useful to be able to use a [database server](https://jeremylong.github.io/DependencyCheck/data/database.html) also in Gradle projects. Looking at the plugin code it seems to be not supported currently.

**Comment by stefanneuhaus** [comment]
@szpak The good news is the central database server can also be used for Gradle projects. The required configuration changes are documented [here](https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration-update.html).

For hints on how to configure it you can also have a look at my project [dependencycheck-central-mysql-docker](https://github.com/stefanneuhaus/dependencycheck-central-mysql-docker), which is a Docker-based out-of-the-box solution for the database server.

**Comment by szpak** [comment]
Thanks, I was looking for particular strings (such as `databaseDriverName`) and I missed that the advanced configuration can be passed as `data {}`.
