### ISSUE TITLE
Switching from Jenkins plugin to Gradle plugin

### ISSUE THREAD

**Issue by pauldambra** [jeremylong/dependency-check-gradle#124]
As far as I can tell the gradle plugin is faster for us than the jenkins plugin. So we'd like to move over to the Gradle plugin but we don't know how to fail the build based on number of types of vulns discovered

When setting up the jenkins plugin we used

```
dependencyCheckPublisher(
                        canComputeNew: false,
                        defaultEncoding: '',
                        failedTotalAll: '', // fail if greater than M vulns
                        failedTotalHigh: '0', // 0 means fail if any high vulns
                        healthy: '',
                        pattern: '',
                        unHealthy: '10' //build is unhealthy while there are more than N vulns
                )
```

So that we could block the build for new high vulns.

In our gradle file we have: 

```
dependencyCheck {

    skipTestGroups = false
//    suppressionFile = 'dependency-check-suppressions.xml'
    data {
        directory= System.properties['user.home'] + '/dependency-check-data'
    }
    analyzers {
        experimentalEnabled = true
        assemblyEnabled = false
        rubygemsEnabled = false
        nuspecEnabled = false
//        nugetconfEnabled = false
        composerEnabled = false
        cocoapodsEnabled = false
        swiftEnabled = false
        bundleAuditEnabled = false
    }
}
```

what's the equivalent way to block the build in Gradle?

**Comment by pauldambra** [comment]
Hmm, I've just realised I can still use the publisher block in the pipeline, DOH!

Is that the correct solution or...?

**Comment by jeremylong** [comment]
Yes - and in reality you will get better results using the gradle plugin vs. having the Jenkins plugin scan and publish the results.

**Comment by pauldambra** [comment]
Brill, will stick with that

Thanks so much! Infosec folk (and others) at work are so happy we can have this in the build pipeline!
