### ISSUE TITLE
Cannot cast object '[]' with class 'java.util.ArrayList' to class 'org.owasp.dependencycheck.reporting.ReportGenerator$Format'

### ISSUE THREAD

**Issue by GregDThomas** [jeremylong/dependency-check-gradle#125]
When trying to use plugin (verison 5.0.0-M3) with Gradle 5.4.1 using the default configuration , I get the following error;

```
$ ./gradlew dependencyCheckAnalyze --console=plain

> Task :dependencyCheckAnalyze
Verifying dependencies for project foo
Checking for updates and analyzing dependencies for vulnerabilities
Generating report for project foo

> Task :dependencyCheckAnalyze FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencyCheckAnalyze'.
> Cannot cast object '[]' with class 'java.util.ArrayList' to class 'org.owasp.dependencycheck.reporting.ReportGenerator$Format'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
1 actionable task: 1 executed
```

I've tried to resolve this by setting configuration, but to date have not yet managed to do so. Any advice gratefully received!

I've attached a sample build.gradle demonstrating this issue.

[build.gradle](https://github.com/jeremylong/dependency-check-gradle/files/3151992/build.gradle.txt)

Greg

**Comment by jeremylong** [comment]
I apologize - as I have no idea how this happened.  I had fixed this defect but must have not merged the branch.  I just pushed 5.0.0-M3.1.

**Comment by GregDThomas** [comment]
Brilliant - many thanks for the swift response, can confirm that 5.0.0-M3.1 is working fine.

**Comment by feinstein** [comment]
Please update the website, as there's still "5.0.0-M3"
