### ISSUE TITLE
Node Audit analysis errors on package-lock files

### ISSUE THREAD

**Issue by cameronbosnic** [jeremylong/dependency-check-gradle#128]
My package-lock.json files across all projects are failing with:

10:00:30.517 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Could not perform Node Audit analysis - service returned a 503.
10:00:30.517 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:694)
10:00:30.518 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.owasp.dependencycheck.Engine$analyzeDependencies$0.call(Unknown Source)

Might be capacity issues from npm.org that are causing these as I do have 7000 or so dependencies in these lock files.  Perhaps we need to slow down the rate of the requests?

Version 5.0.0-M3.1

**Comment by cameronbosnic** [comment]
Or perhaps add some retry logic?

**Comment by jeremylong** [comment]
I am in the process of enabling caching of results and we have recently added a retry. Both of these will be included in the next release.

However, be aware that unless there is a reason you need to use ODC, for instance multiple technology stacks, ODC returns the same results as `npm audit`.  In addition, if just using core `npm` features you can also run `npm audit fix`.

**Comment by jeremylong** [comment]
This should be resolved in the current release - 5.1.0
