### ISSUE TITLE
Aggregate report on multi-module-project

### ISSUE THREAD

**Issue by brianpreuss** [jeremylong/dependency-check-gradle#13]
Hi,

is there a possiblity to create an aggregate report on a multi-module-project as in Maven?

Regards,

Brian

**Comment by jeffbrown** [comment]
Is this planned?

**Comment by jeremylong** [comment]
This is a planned feature; I just have not had time to work on this yet.

**Comment by seanboylan** [comment]
Happy new year Jeremy,
An aggregate option for the gradle plugin would be great.

**Comment by bzon** [comment]
I see that this is now close. Is there a reference or documentation how to do this?

**Comment by childnode** [comment]
The [README.md](https://github.com/jeremylong/dependency-check-gradle/blob/master/README.md) seems some days outdated
> The latest version is `2.0.0`.
but it is 2.1.1 (ref. http://search.maven.org/#search%7Cga%7C1%7Corg.owasp.dependency-check-gradle)

nevermind, README tells you to 
> Please see the [documentation site](https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html) … which lacks this info too ;)


long story short:
quote from PR https://github.com/jeremylong/dependency-check-gradle/pull/49
> This PR adds an aggregation task: `dependencyCheckAggregate`.

**Comment by bzon** [comment]
@childnode Thanks! Let me try it. Is this like dependencyCheckAnalyze with aggregation?
