### ISSUE TITLE
Skip dependency groups

### ISSUE THREAD

**Issue by Thorbear** [jeremylong/dependency-check-gradle#132]
Some projects I work on have a lot of private dependencies, deployed to a private maven repository. These dependencies will not be found in any CVE, and do not need to be scanned or included in reports. It would be great to have a way to skip such dependencies.
For example it would be great to configure "skip all dependencies in the `no.thorbear.private` group".

As far as I can tell from the documentation, there is no way to make the analyzer skip certain dependencies or dependency-groups.

Skipping such dependencies would also help to avoid accidentally sharing information about private dependencies, in line with the documentation for the new [Matching repositories to dependencies](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec::matching_repositories_to_dependencies) feature in Gradle 5.

**Comment by holubec-petr** [comment]
Hi,
I'm also very interested in this new feature.

We've come with the following workaround for now:
You can create your own custom configuration and add there all dependencies you want to scan (you can filter out your private dependencies when filling the custom configuration). Then you can configure the dependency check plugin to scan just your custom configuration.

The workaround above works for us but I'd like to have a cleaner solution so I started to work on PR for this plugin. Hope it will be ready in the upcoming days and looking forward to your and @jeremylong feedback.
