### ISSUE TITLE
CSV rapport is full of blank lines

### ISSUE THREAD

**Issue by sigand** [jeremylong/dependency-check-gradle#134]
After upgrading to plugin version 5.0.0, the csv rapport now contains many blank lines, where there previously only was the header line and any vulnerabilities

Run command: `./gradlew dependencyCheckAnalyze --info`
Setup also includes a dependency-suppression file

**Comment by olereidar** [comment]
I wondered why my builds suddenly stopped building. I have a very short build script that checks whether this file contains more than 1 line. More than one line means dependency issues. 
Will you guys fix this?

**Comment by jeremylong** [comment]
This has been fixed in the current snapshot and will be included in the next release.
