### ISSUE TITLE
Default data directory vs build pipeline caching

### ISSUE THREAD

**Issue by skjolber** [jeremylong/dependency-check-gradle#136]
For improved speed and less unneccessary network traffic, we cache the CVE database between runs in our CircleCI pipeline. 

As the data directory now is placed within a ['random'](https://github.com/jeremylong/dependency-check-gradle/blob/master/src/main/groovy/org/owasp/dependencycheck/gradle/extension/DataExtension.groovy) subdirectory of the .gradle directory, this requires the data directory to be specified in the gradle configuration. 

It would be more convenient / automagic if the data directory default location is fixed. Then no data directory configuration would be necessary in the gradle configuration. This might seem like a small issue, but for example should the developer forget to add the data directory, CircleCI cache immutably will mean that the (multi-level) cache will be empty; so even if fixed, each time a cache expires and falls back to the level below, it is empty. So not disfunctional, but not ideal either.

Even better, why not go for user home directories `.gradle/xyz` and `.m2/xyz` directories as defaults; or even home directory `.owasp-dependency-check`? Most developers have multiple projects, so makes sense to share the cache and it would save millions of downloads.

See also the [OWASP Orb](https://github.com/entur/owasp-orb), based on your maven and gradle work.

**Comment by jeremylong** [comment]
I'm confused by your statement that the "data directory now is placed within a 'random' subdirectory" - on my system `[JAR]/../../dependency-check-data/4.0` always ends up resolving to:

```
~/.gradle/caches/dependency-check-data/4.0/
```

The [JAR] reference is the location of the running `dependency-check-gradle-[version].jar`.

If you run `gradle dependencyCheckAnalyzer --info | grep jdbc` you will see where the main path to the data directory is.  Yes, you will also see a somewhat random path pointing to the temp directory - for your purposes ignore this one as it is a transient copy of the database that is thrown.

**Comment by jeremylong** [comment]
Additionally, you can configure the data directory to be any directory you want.

**Comment by skjolber** [comment]
Interesting, in my system it shows up at

> ~/.gradle/caches/modules-2/files-2.1/org.owasp/dependency-check-utils/dependency-check-data

which is reflected in the build output:

> 14:42:34.533 [DEBUG] [org.owasp.dependencycheck.utils.Settings] Connection String: 'jdbc:h2:file:/home/skjolber/.gradle/caches/modules-2/files-2.1/org.owasp/dependency-check-utils/dependency-check-data/4.0/odc;AUTOCOMMIT=ON;LOG=0;CACHE_SIZE=65536;'

So I guess for some reason the jar location 'anchor' must be different.

**Comment by skjolber** [comment]
I get the same result for a clean spring project. 

Would you accept a PR changing the default value to [gradle user home](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables) via 

> project.gradle.gradleUserHomeDir

?

**Comment by jeremylong** [comment]
Sure - that would work.
