### ISSUE TITLE
Ths "junitFailOnCVSS" is missing on DependencyCheckExtension.groovy 

### ISSUE THREAD

**Issue by skydjol** [jeremylong/dependency-check-gradle#138]
In this documentation 
https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html
A property `junitFailOnCVSS` can be defined, but not present in https://github.com/jeremylong/dependency-check-gradle/blob/master/src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy (like failBuildOnCVSS).

**Comment by jeremylong** [comment]
Sorry about that - it will be included in the next release.
