### ISSUE TITLE
Version 5.2.1 not yet released

### ISSUE THREAD

**Issue by stefanneuhaus** [jeremylong/dependency-check-gradle#140]
Version 5.2.1 of [DependencyCheck](https://github.com/jeremylong/DependencyCheck/releases) has been released on 2019-08-04. As in the past new versions of the Gradle plugin have been released on the same day I wanted to make sure that the release of the Gradle plugin hasn't been forgotten.

**Comment by jeremylong** [comment]
Sorry - yes, the plugin was pushed to [central](https://search.maven.org/artifact/org.owasp/dependency-check-gradle/5.2.1/jar).  I had some difficulty with Travis and completely forgot to push the gradle plugin to the plugin repo and push the tag to github.

It should be there now.

**Comment by stefanneuhaus** [comment]
Great, that was fast! 🚀
