### ISSUE TITLE
Authentication issue with downloading nvdcve files from private Artifactory

### ISSUE THREAD

**Issue by brianhussey** [jeremylong/dependency-check-gradle#143]
Hey,
I'm getting an error downloading CVE files from an internal and authenticated Artifactory location. Full trace here:
[artifactoryAuthDepCheck.log](https://github.com/jeremylong/dependency-check-gradle/files/3502311/artifactoryAuthDepCheck.log)

It looks like credentials aren't being used for downloading those files.

I've verified the files are there and that the credentials I'm using actually have access.

Thanks,
Brian

**Comment by marco-schmidt** [comment]
@brianhussey 

Hi Brian,

have you tried specifying authentication details as proxy settings (server, port, username, password within a proxy element within the dependencyCheck configuration) as described in <https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration-aggregate.html>? This worked for me, although it may duplicate credentials and server information defined elsewhere in the gradle file as part of maven repository settings.

I came from a somewhat different angle, though, trying to work with (against) our internal proxy that prevented me from accessing an internal mirroring server.

Greetings,
Marco

**Comment by brianhussey** [comment]
@marco-schmidt 
I'll give it a go, thank you.

**Comment by marco-schmidt** [comment]
@brianhussey 
Apparently it only worked for me on my local machine because other things were cached. On another machine it would try to load additional files from external hosts which would then fail because the proxy server of course is not a real one. So, I'm also still looking for a solution.

I wonder if I should add a ticket here
- about being able to specify non-proxy hosts in the dependency check proxy configuration section or
- making the plugin use the gradle proxy settings.

**Comment by jeremylong** [comment]
I would recommend, instead of loading the CVE files into Artifactory, that you simply use the [nist-data-mirror](https://github.com/stevespringett/nist-data-mirror) or load the files to a web server that does not require authentication.

**Comment by jeremylong** [comment]
@brianhussey in 5.2.3, which should be released today/tomorrow you can define basic auth for artifactory...  This is not an ideal implementation and I plan to revisit the problem but please see https://github.com/jeremylong/DependencyCheck/issues/1977 for more information.

@marco-schmidt I just added the non-proxy hosts to the configuration.
