### ISSUE TITLE
Dependency check doesn't generate report file

### ISSUE THREAD

**Issue by emartynov** [jeremylong/dependency-check-gradle#147]
Dependency check failed gradle check since it found new vulnerabilities.

I don't see generated owasp report to check things and get suppression help.

What could be the issue?

**Comment by emartynov** [comment]
Ah I see reports in the modules build folder but not combined report in the root build folder.

**Comment by jeremylong** [comment]
To get the results in the root folder maybe run `dependencyCheckAggregate`? Can this be closed then?

**Comment by emartynov** [comment]
I run actually `dependencyCheckAggregate`. And I had a combined report file before that is why I started this ticket.

**Comment by jeremylong** [comment]
We would need to know a lot more about the project to help figure that out.  If you had a combined report before - what changed in your configuration?

**Comment by emartynov** [comment]
I think we updated gradle and couple of plugins. As well number of modules grew for the project.

**Comment by emartynov** [comment]
I will update you with versions we have now.

**Comment by emartynov** [comment]
Gradle 5.6, AGP 3.5, OWASP plugin 5.2.1.

**Comment by jeremylong** [comment]
Not enough information has been provided to assist with this ticket.  We would need to see the actual build.gradle (actually - likely more the entire aggregate build's structure and build files).
