### ISSUE TITLE
Does the DependencyCheck Gradle Plugin Scan The Jars of Other Gradle Plugins? 

### ISSUE THREAD

**Issue by lingocoder** [jeremylong/dependency-check-gradle#150]
First-time user. I just ran *`:dependencyCheckAnalyze`* on a Gradle project. It analyzed the binary dependencies configured in Gradle's *`dependencies{ }`* block alright. Pretty cool :+1:

But it's not obvious from the docs whether the check, by default, also analyzes the jars that Gradle plugins are bundled in or not. Does it? If not, is there some property or something to configure to have it do its thing on Gradle plugins?

If anybody's had success doing that, please share the steps you took? Thanks in advance.

**Comment by jeremylong** [comment]
Yes, the dependency-check-gradle plugin will analyze the transitive dependencies defined.

**Comment by lingocoder** [comment]
> „*...will analyze the transitive dependencies defined...*“

Thanks @jeremylong. I understand your answer to be saying, that if the *`dependencies{ }`* block results in this example graph of direct and transitive dependencies...

```
+--- project :openmuc-core-spi
|    \--- project :openmuc-core-api
|         +--- org.osgi:osgi.core:7.0.0
|         +--- org.osgi:org.osgi.service.component.annotations:1.4.0
|         +--- org.apache.felix:org.apache.felix.scr:2.1.14
|         |    \--- org.codehaus.mojo:animal-sniffer-annotations:1.9
|         +--- org.apache.felix:org.apache.felix.http.servlet-api:1.1.2
|         |    \--- org.apache.tomcat:tomcat-servlet-api:8.0.9
|         +--- org.osgi:org.osgi.service.http:1.2.1
|         \--- org.slf4j:slf4j-api:1.7.25
\--- org.apache.felix:org.apache.felix.gogo.runtime:1.1.0

```

...then *`openmuc-core-spi`* plus everything beneath it (*its transitive dependencies*) would be analyzed. That's what I expected already. 

I should have been more specific. But I asked my original question because I was wondering about the JARs of plugins defined in the *`plugins{ }`* block like so...


```
plugins{
   ...
   id 'tv.cogswell.cogs' version '2525.2.0'
   ...
}
```

So I gather from your answer that the JAR file of the *`tv.cogswell.cogs`* plugin example (*plus its transitive dependencies*) would be analyzed along with the regular *`dependencies{ }`* block-defined artifacts.

Apologies for belaboring it. I just want to make sure I'm not misunderstanding your answer. I'm easily confused you see :)

**Comment by jeremylong** [comment]
Actually - the plugins section is not analyzed at all.

**Comment by lingocoder** [comment]
Ahh! OK Thanks for clarifying that for me. Much appreciated :+1:
