### ISSUE TITLE
scanProjects & skipProjects not working

### ISSUE THREAD

**Issue by lkuendig** [jeremylong/dependency-check-gradle#153]
I have a multi-project with the plugin applied on the rootProject. If I do not define scanProjects or skipProjects, the plugin runs fine and detects some vulnerabilities in several subModules.
- If I add scanProjects - doesn't matter which subModule I've defined - it always does not find any vulnerabilities
- If I add skipProjects, it does not skip the subModule I've defined and runs for all subModules

**Comment by bjornvester** [comment]
It isn't documented all that well, but you have to give it the project _path_ (using colons as separators, e.g. `":subProject"`). Is that what is causing it?

**Comment by jeremylong** [comment]
@bjornvester is correct - you must include the preceding colon in the project name.  I have updated the documentation to indicate this.
