### ISSUE TITLE
Issues with Gradle 6.0-rc-1

### ISSUE THREAD

**Issue by juergenzimmermann** [jeremylong/dependency-check-gradle#155]
When I use _org.owasp.dependencycheck_ version _5.2.2_ with _Gradle 6.0 rc1_ I get the following output:

```
> Task :dependencyCheckAnalyze
Verifying dependencies for project kunde
The compile configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the compileClasspath configuration instead.
The compileOnly configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the compileClasspath configuration instead.
The runtime configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the runtimeClasspath configuration instead.
```

**Comment by bjornvester** [comment]
Are you using those deprecated configurations anywhere? Because that is just Gradle warning you that you need to use replacements, or you will get an error in the future release 7.0. This doesn't have anything to do with the plugin as such.

**Comment by marco-schmidt** [comment]
I get the same warnings with gradle 6.0-rc-2 and dependencycheck 5.2.2 without using those configurations (as far as I can tell): https://github.com/marco-schmidt/am/blob/master/build.gradle
```
 >./gradlew dependencyCheckAnalyze --warning-mode all 

> Task :dependencyCheckAnalyze
Verifying dependencies for project am
The compile configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the compileClasspath configuration instead.
The compileOnly configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the compileClasspath configuration instead.
The runtime configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the runtimeClasspath configuration instead.
Checking for updates and analyzing dependencies for vulnerabilities
Generating report for project am
Found 0 vulnerabilities in project am

BUILD SUCCESSFUL in 4s
1 actionable task: 1 executed
```

**Comment by juergenzimmermann** [comment]
@jeremylong It's not a question. The comment of @bjornvester is wrong. The deprecation warnings are not because of a specific configuration. BTW, Gradle 6.0 is announced for Nov. 8, and more users of the Gradle plugin will observe this issue. https://github.com/gradle/gradle/milestones

**Comment by bjornvester** [comment]
Sorry, I was just asking if the OP used those configurations as I don't get that warning myself when running on 6.0-RC2. But I just realized that it is probably just because I am explicitly configuring which configurations I want analyzed like this:

```groovy
dependencyCheck {
    scanConfigurations = ['runtimeClasspath']
}
```

By default, it will analyze them all (deprecated or not).

I don't think there is a whole lot that can be done in the plugin, except for documenting that you will get those harmless (but very annoying) warnings in Gradle 6.0 if you are not explicit about the configurations, but you can get rid of them by excluding the three configurations if you are not actually using them. It won't become a problem in Gradle 7.0 as the configurations will become unresolvable and thereby not selected for analysis.

**Comment by juergenzimmermann** [comment]
@bjornvester I see. When I use `scanConfigurations = ['runtimeClasspath']` the warnings are gone. I'd recommend to emphasize this config option in the documentation.

**Comment by jeremylong** [comment]
The configurations causing the warnings are likely being added by another plugin.  In the testing I've done there have been no dependencies in the `compile`, `compileOnly`, and `runtime` configurations when the warning is raised. However, if you run the following on the `build.gradle` provided by @marco-schmidt above - you will see that the configurations are present:
```
./gradlew  --console plain dependencies | fgrep ' - '
```
The dependency-check task grabs all available configurations and checks for dependencies within the configurations - this is what is triggering the warning.
