### ISSUE TITLE
dependency-check-gradle could not be applied as plugin for < gradle 4.9

### ISSUE THREAD

**Issue by mbayrak78** [jeremylong/dependency-check-gradle#162]
As commented in 
https://github.com/jeremylong/dependency-check-gradle/commit/13916c20e57e87b2ea70f397c2899e5a139e3af0#r36049781

task.register() is not available for < gradle 4.9

Please review changes again and support backwards compatibility.

**Comment by stefanneuhaus** [comment]
This could be solved similar to [here](https://github.com/jeremylong/dependency-check-gradle/pull/51/files#diff-ca95dd51a667d486220feef1effffedfR124): check for the existence of the `register()` method and do it either the old way or use the new Task Configuration Avoidance API.
