### ISSUE TITLE
Dec 31 2019 5:39pm Pacific / Jan 1 2020 01:39AM GMT: Unable to download 2020 meta file /feeds/json/cve/1.1/nvdcve-1.1-2020.meta

### ISSUE THREAD

**Issue by petedoyle** [jeremylong/dependency-check-gradle#165]
Hi Jeremy!
Just FYI, we're seeing this in CI (GMT time zone, where it just turned 2020) using dependency-check-gradle 5.2.4:
```
Unable to download meta file: https://[our proxy]/feeds/json/cve/1.1/nvdcve-1.1-2020.meta; received 404 -- resource not found
```

We're using a custom-written proxy, but it looks like the 2020 files aren't available in the [NVD feed](https://nvd.nist.gov/vuln/data-feeds) either:
- https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.meta
- https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.gz
- https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.zip

Just FYI, a fun edge case! :)

We're not blocked- temporarily disabling dependency-check until the 2020 data starts to appear.

**Comment by petedoyle** [comment]
Also reported here: https://github.com/jeremylong/DependencyCheck/issues/2403

**Comment by jeremylong** [comment]
This has been resolved - the NVD 2020 files have been published.
