### ISSUE TITLE
Dependency checks fail for new 2020 NVD CVEs

### ISSUE THREAD

**Issue by burythehammer** [jeremylong/dependency-check-gradle#166]
I've come back after the new years break and one of our daily Jenkins builds that checks for dependency issues is now failing.

The Jenkins builds have been working okay until the 1st of January 2020. Nobody was in over the holiday period, and we haven't updated anything on our side. Now suddenly the plugin can't seem to process the NVD JSON data. I suspect this is some date/format related issue? I saw a fix on the other repository for the maven plugin.

Aware we're using an older version, 5.0.0. I tried a version bump but it seems to require some sort of mirrored meta file (any help in this direction would be appreciated).

Here's the error log from Jenkins:

```
Download https://repo.maven.apache.org/maven2/org/owasp/dependency-check-utils/5.0.0-M2/dependency-check-utils-5.0.0-M2.jar
> Task :dependencyCheckUpdate
> Task :dependencyCheckUpdate

Error reading NVD JSON data: /tmp/dctemp65d76834-0a7c-41a6-83ca-fb75501c22b9/cve2020_5615620050192381690.json.gz

> Task :dependencyCheckUpdate FAILED

FAILURE: 
Build failed with an exception.
* What went wrong:
Execution failed for task ':dependencyCheckUpdate'.
Unable to connect to the dependency-check database
Run with -stacktrace option to get the stack trace. Run with --info or --debugoption to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 55s 
actionable task: 1 executed
The command '/bin/sh -c ./gradlew --no-daemon :dependencyCheckUpdate' returned a non-zero code: 1
```

and here's a redacted build.gradle. We're using mirrored NIST NVD files as we've had a lot of issues with connectivity to their servers.

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.owasp:dependency-check-gradle:5.2.1'
    }
}

apply plugin: 'org.owasp.dependencycheck'

dependencyCheck {
    data {
        directory='/src/nvd'
    }
    cve {
        urlBase='http://example.com/repository/nist-nvd-mirror/json/nvdcve-1.0-%d.json.gz'
        urlModified='http://example.com/repository/nist-nvd-mirror/json/nvdcve-1.0-modified.json.gz'
    }
}
```

Any further info, just let me know.

**Comment by jeremylong** [comment]
You are using a milestone release. Please upgrade to the latest - 5.2.4. Regarding the meta data file - those will need to be mirrored also. See https://nvd.nist.gov/vuln/data-feeds#JSON_FEED.

**Comment by burythehammer** [comment]
It appears to have now randomly fixed itself - curious. One assumes that this is an issue that will only happen around the new years?

Regardless, we need to update this version, so I will look into doing that. From a cursory look we need to upgrade gradle and some other things first.
