### ISSUE TITLE
Test configuration detection is broken

### ISSUE THREAD

**Issue by stefanneuhaus** [jeremylong/dependency-check-gradle#17]
The [current implementation](https://github.com/jeremylong/dependency-check-gradle/blob/master/src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Check.groovy#L312) of the `skipTestGroups` configuration property is broken:
- it compares case-sensitive to `testcompile` and `testruntime`, while the actual configuration names are camel case.
- it does not yet support the new configurations `testCompileClasspath` and `testCompileOnly` introduced with Gradle 2.12: [Java plugin - dependency configurations](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_plugin_and_dependency_management)

Relying on the inheritance hierarchy of a configuration and checking whether a configuration [extends from](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.Configuration.html#org.gradle.api.artifacts.Configuration:extendsFrom) a well-known test configuration could be even more robust.

If you like these changes to be implemented, I can provide a PR.

**Comment by jeremylong** [comment]
Thanks for pointing this out.  If you have time a PR would be great. I
still have a few bugs/enhancements in the core engine that I need to get
done before I can refocus on the gradle plugin.

--jeremy

Jeremy

**Comment by stefanneuhaus** [comment]
Great, I'll take this on.

**Comment by stefanneuhaus** [comment]
I created the PR.

**Comment by stefanneuhaus** [comment]
@jeremylong How do you feel about this PR? And what do you think about my proposed solution to #11?

As the latter is an extension of this PR, I do not know if it is worth to create the PR for #11, before I got your feedback.

**Comment by jeremylong** [comment]
@stefanneuhaus I really like the solution of looking at the request hierarchy to determine if something is in a test scope. As to how this relates to your proposed solution for #11 - wouldn't looking at the hierarchy by itself resolve issue #11? Or do you think looking at the hierarchy plus expanding the known test scopes to include some of the android specific ones?

**Comment by stefanneuhaus** [comment]
The solution in this PR calls a configuration a test configuration, if and only if the name of the configuration or any of its parent configurations equals ```testCompile```.

I think this is an improvement compared to the former merely name-based heuristic. But after having created that PR I noticed issue #11 and that the idea could be easily extended to also provide a better Android support. Thus the proposed solution for #11 goes beyond.

It calls a configuration a test configuration, if and only if any of the following conditions holds:
- the name of the configuration or any of its parent configurations equals `testCompile`
- the name of the configuration or any of its parent configurations equals `androidTestCompile`
- the configuration name starts with `androidTest`
- the configuration name starts with `test`

You probably noticed that I re-introduced the name-_prefix_ check for ```test``` (and also for ```androidTest```). Though I prefer comparing to _entire_ names, this was a trade-off as I observed that otherwise we would have missed a bunch of apparent test configurations, that do not extend any other configuration. In my rather simple Android project these were (cf. my lengthy comment to #11):
```
androidTestApk
androidTestCompile
androidTestProvided
androidTestWearApp
testApk
testCompile
testDebugApk
testDebugCompile
testDebugProvided
testDebugWearApp
testProvided
testReleaseApk
testReleaseCompile
testReleaseProvided
testReleaseWearApp
testWearApp
```

Also note that adding these ones as a hard-coded list of well-known test configurations won't do the trick, as each Android project manages a couple of s.c. _flavors_, whose names are incorporated in the configuration names (e.g. flavor "debug" introduces "testDebug*"). Though one _could_ also determine these flavor names from the Gradle runtime, I did not want to be _super_ exact in this respect. Doing so could mean to be tilting at windmills, as any new Gradle (Android) plugin could introduce its own new test configuration name pattern. I felt like checking for the name prefix would be the right compromise.

**Comment by jeremylong** [comment]
Thanks, sorry for being a bit slow - its been a very long couple of weeks.  Completely agree that PR #18 should be merged - but with the added exclusions outlined above to address issue #11.

Mind updating the PR with the change described above?

--Jeremy

**Comment by stefanneuhaus** [comment]
@jeremylong I updated the PR accordingly.

**Comment by jeremylong** [comment]
PR #18 from @stefanneuhaus resolved this issue.
