### ISSUE TITLE
OSS Index Analyzer exception

### ISSUE THREAD

**Issue by sbennettmcleish** [jeremylong/dependency-check-gradle#170]
Getting the following exception when running v5.2.4, it still seems to work though. I had to turn up gradle debug, normal output just says "Unexpected exception occurred initializing Sonatype OSS Index Analyzer". 

> build	15-Jan-2020 15:22:01	15:22:00.923 [DEBUG] [org.owasp.dependencycheck.Engine] Initializing Sonatype OSS Index Analyzer
build	15-Jan-2020 15:22:01	15:22:00.931 [DEBUG] [org.sonatype.ossindex.service.client.util.UserDataLocation] OS type: LINUX
build	15-Jan-2020 15:22:01	15:22:00.934 [DEBUG] [org.owasp.dependencycheck.utils.Settings] Settings.getDataFile() - file: '/home/bamboo/.gradle/dependency-check-data/4.0'
build	15-Jan-2020 15:22:01	15:22:00.934 [DEBUG] [org.owasp.dependencycheck.data.ossindex.OssindexClientFactory] OSS Index Cache: org.sonatype.ossindex.service.client.cache.DirectoryCache$Configuration@4da835
build	15-Jan-2020 15:22:01	15:22:00.937 [DEBUG] [org.sonatype.ossindex.service.client.transport.UserAgentSupplier] User-agent: dependency-check/5.2.4 (Linux; 4.4.0-1099-aws; amd64; 11.0.5)
build	15-Jan-2020 15:22:01	15:22:00.952 [DEBUG] [org.sonatype.ossindex.service.client.internal.OssindexClientImpl] Transport: org.owasp.dependencycheck.data.ossindex.ODCConnectionTransport@dbb7d8c
build	15-Jan-2020 15:22:01	15:22:00.952 [DEBUG] [org.sonatype.ossindex.service.client.internal.OssindexClientImpl] Marshaller: org.sonatype.ossindex.service.client.marshal.GsonMarshaller@277cb5c1
build	15-Jan-2020 15:22:01	15:22:00.952 [DEBUG] [org.sonatype.ossindex.service.client.internal.OssindexClientImpl] Base URL: https://ossindex.sonatype.org/
build	15-Jan-2020 15:22:01	15:22:00.952 [DEBUG] [org.sonatype.ossindex.service.client.internal.OssindexClientImpl] Batch size: 128
error	15-Jan-2020 15:22:01	15:22:00.954 [ERROR] [org.owasp.dependencycheck.Engine] Unexpected exception occurred initializing Sonatype OSS Index Analyzer.
build	15-Jan-2020 15:22:01	15:22:00.954 [DEBUG] [org.owasp.dependencycheck.Engine] 
build	15-Jan-2020 15:22:01	java.lang.NoSuchMethodError: 'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'
build	15-Jan-2020 15:22:01		at org.sonatype.ossindex.service.client.cache.DirectoryCache.<init>(DirectoryCache.java:83)
build	15-Jan-2020 15:22:01		at org.sonatype.ossindex.service.client.cache.DirectoryCache$Configuration.create(DirectoryCache.java:315)
build	15-Jan-2020 15:22:01		at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.<init>(OssindexClientImpl.java:96)
build	15-Jan-2020 15:22:01		at org.owasp.dependencycheck.data.ossindex.OssindexClientFactory.create(OssindexClientFactory.java:120)
build	15-Jan-2020 15:22:01		at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.prepareAnalyzer(OssIndexAnalyzer.java:130)
build	15-Jan-2020 15:22:01		at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:102)
build	15-Jan-2020 15:22:01		at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:842)
build	15-Jan-2020 15:22:01		at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:678)
build	15-Jan-2020 15:22:01		at org.owasp.dependencycheck.Engine$analyzeDependencies$1.call(Unknown Source)
build	15-Jan-2020 15:22:01		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
build	15-Jan-2020 15:22:01		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
build	15-Jan-2020 15:22:01		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
build	15-Jan-2020 15:22:01		at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:89)
build	15-Jan-2020 15:22:01		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
build	15-Jan-2020 15:22:01		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
build	15-Jan-2020 15:22:01		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
build	15-Jan-2020 15:22:01		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
build	15-Jan-2020 15:22:01		at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
build	15-Jan-2020 15:22:01		at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
build	15-Jan-2020 15:22:01		at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
build	15-Jan-2020 15:22:01		at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
build	15-Jan-2020 15:22:01		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
build	15-Jan-2020 15:22:01		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
build	15-Jan-2020 15:22:01		at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
build	15-Jan-2020 15:22:01		at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
build	15-Jan-2020 15:22:01		at java.base/java.util.Optional.orElseGet(Optional.java:369)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
build	15-Jan-2020 15:22:01		at java.base/java.util.Optional.map(Optional.java:265)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
build	15-Jan-2020 15:22:01		at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
build	15-Jan-2020 15:22:01		at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
build	15-Jan-2020 15:22:01		at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
build	15-Jan-2020 15:22:01		at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
build	15-Jan-2020 15:22:01		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
build	15-Jan-2020 15:22:01		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
build	15-Jan-2020 15:22:01		at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
build	15-Jan-2020 15:22:01		at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
build	15-Jan-2020 15:22:01		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
build	15-Jan-2020 15:22:01		at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
build	15-Jan-2020 15:22:01		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
build	15-Jan-2020 15:22:01		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
build	15-Jan-2020 15:22:01		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
build	15-Jan-2020 15:22:01		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
build	15-Jan-2020 15:22:01		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
build	15-Jan-2020 15:22:01		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
build	15-Jan-2020 15:22:01		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
build	15-Jan-2020 15:22:01		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
build	15-Jan-2020 15:22:01		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
build	15-Jan-2020 15:22:01		at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
build	15-Jan-2020 15:22:01		at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
build	15-Jan-2020 15:22:01		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
build	15-Jan-2020 15:22:01		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
build	15-Jan-2020 15:22:01		at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
build	15-Jan-2020 15:22:01		at java.base/java.lang.Thread.run(Thread.java:834)
build	15-Jan-2020 15:22:01	15:22:00.956 [DEBUG] [org.owasp.dependencycheck.Engine] Initializing Vulnerability Suppression Analyzer

**Comment by jeremylong** [comment]
Love JAR conflict issues.  It looks like you have a conflicting version of Guava in your build path:

```
build 15-Jan-2020 15:22:01 java.lang.NoSuchMethodError: 'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'
```
