### ISSUE TITLE
Dependency-check , scan ip address

### ISSUE THREAD

**Issue by tarantolait** [jeremylong/dependency-check-gradle#171]
Hi,
anyone know the Argument for a Jenkins job , with Dependency-check plugin,
for scan entire ip address target?
Best Regards
Andrea

**Comment by tarantolait** [comment]
![Capture](https://user-images.githubusercontent.com/60004409/72616425-34338e80-3937-11ea-9c67-544b621c85e7.JPG)

**Comment by jeremylong** [comment]
I'm not sure I understand your question.  ODC is an SCA build tool - not a scanning tool.  ODC is used to scan the build dependencies of an application - preferable using the Maven or Gradle plugin but scanning a directory or workspace using Jenkins or the CLI works as well. This is not a tool used to scan an IP address.

**Comment by tarantolait** [comment]
But if i want scan a server for analyze library vulnerabilities , how i can do? 
(agent running inside the server)

**Comment by jeremylong** [comment]
You would use the CLI integration on the server itself and scan the specific directories where the applications are installed.  The ODC CLI documentation is found here: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html
