### ISSUE TITLE
small bug in ConfiguredTask when setting nonProxyHosts

### ISSUE THREAD

**Issue by bdhave** [jeremylong/dependency-check-gradle#177]
line  75:
        settings.setArrayIfNotEmpty(**SUPPRESSION_FILE**, config.proxy.nonProxyHosts)
MUST BE
        settings.setArrayIfNotEmpty(**PROXY_NON_PROXY_HOSTS**, config.proxy.nonProxyHosts)

I can submit a pull request if you want.
Thank you,
Bernard

**Comment by bdhave** [comment]
created pull request #179

**Comment by jeremylong** [comment]
Again - thanks for the PR!
