### ISSUE TITLE
proxy settings from gradle settings

### ISSUE THREAD

**Issue by bdhave** [jeremylong/dependency-check-gradle#178]
I found the way to do it.
but it use the following internal classes:
import org.gradle.internal.resource.transport.http.HttpProxySettings
import org.gradle.internal.resource.transport.http.JavaSystemPropertiesSecureHttpProxySettings
import org.gradle.internal.resource.transport.http.JavaSystemPropertiesHttpProxySettings

If you are ready to use those classes, I can can submit a Pull request,

**Comment by jeremylong** [comment]
Thanks for the PR!
