### ISSUE TITLE
Many duplicate analyses degrade performance

### ISSUE THREAD

**Issue by stefanneuhaus** [jeremylong/dependency-check-gradle#19]
A first observation after analyzing the bad runtimes (e.g. ~7 min for a rather simple project; `dependencyCheckUpdate` excluded) was the following:
Of a single artifact each combination of (artifact, configuration) will be analyzed by the Engine. E.g. a simple "compile" dependency will be analyzed at least 5 times (compile, compileClasspath compileOnly, runtime, default).

**Comment by stefanneuhaus** [comment]
I already implemented a simple fix for this. PR to follow ...

**Comment by jeremylong** [comment]
@stefanneuhaus I'd be interested in the solution you've implemented. When you pointed this out I realized that this may be the case in other plugins. I almost wonder if the solution to this problem should be implemented in the [Engine](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/java/org/owasp/dependencycheck/Engine.java#L307)'s.

Basically, add new set of `scan` functions that also takes a scope/project. Then when adding the dependency, within the engine, we can attach the scope/project AND check if the hash of the dependency matches an existing dependency - at which point we can merge them and this would result in analyzing fewer duplicate dependencies.

**Comment by stefanneuhaus** [comment]
I provided a PR with a sketch of my solution.

But you are right, this does only fix things for the Gradle plugin. I have no clue if a similat issue can occur with the "other plugins"/build tools (Maven, Ant/Ivy?). If so, fixing it in the Engine seems more appropriate.

I am wondering if we could circumvent adding the additional ```scan()``` method overloadings and dependency merging. Wouldn't it be possible to let ```Engine.scanFile(File)``` just return the already existing equivalent Dependency in case there is one?

**Comment by jeremylong** [comment]
I like your idea of modifying `Engine.scanFile(File)` - thanks for the suggestion!  While this has been merged a bit more testing will need to be done with the ArchiveAnalyzer to ensure we don't run into any weird behaviors - but I don't think we should because if the ArchiveAnalyzer extracts a dependency that is a duplicate entry it should not re-add or modify the existing dependency in anyway.

**Comment by jeremylong** [comment]
This has been resolved in the core engine (1.4.4-SNAPSHOT); the fix will be included in the next release.

Truly appreciate the discussion and PR (even though it was not merged)!

--Jeremy
