### ISSUE TITLE
Gradle plugin 6.0.2 for multi-module Gradle project very slow compared to 5.3.2.1

### ISSUE THREAD

**Issue by dietzsch** [jeremylong/dependency-check-gradle#201]
We are using the owasp dependency check plugin in the context of a multi-module Gradle project. To get a overall result for the project we invoke the dependencyCheckAggregate task. With version 5.3.2.1 this took ~5 min for our project on central Jenkins server, when we changed to 6.0.x the time went up to ~16 min. We had seen this already with older versions of the owasp dependency plugin, which seems to be related to the aggregation of results for the different sub modules.

**Comment by jeremylong** [comment]
Was that just on the first execution of ODC 6.x? Or is this after the database has been populated?  ODC 6.0 creates a full new database as there were breaking changes.

**Comment by dietzsch** [comment]
In our tool chain we spin off a new docker container for each build, so that the database is downloaded every time. This behaviour hasn't changed between 5.3.2.1 and 6.0.2. Let me know, if you need additional data that I should provide.

**Comment by jeremylong** [comment]
No the behavior hasn't changed - but if you want a faster build cache the
data directory or move to using a centralized database...

**Comment by dietzsch** [comment]
I know that downloading the database takes some time and that we can improving the timing by centralizing this, but for all our single module projects the times haven't changed much between 5.3.2.1 and 6.0.2, only the multi-module projects, which leads me to the conclusion that the issue could be related to the aggregation of the results from the different modules.

**Comment by jeremylong** [comment]
Can anyone experiencing this issue provide how they are calling aggregate? Specifically what I'm wondering is if aggregate is being called on every module (which is wasteful) or if it is just being called once?

Next - do you see a difference between 6.0.1 and 6.0.2 or is it really the 5.x branch to the 6.x branch?

Finally - when looking at the difference between the executions if you add `-info` a summary of execution times for each analyzer is listed:
```
Analysis Started
Finished File Name Analyzer (0 seconds)
Finished Dependency Merging Analyzer (0 seconds)
Finished Version Filter Analyzer (0 seconds)
Finished Hint Analyzer (0 seconds)
Created CPE Index (1 seconds)
Finished CPE Analyzer (2 seconds)
Finished False Positive Analyzer (0 seconds)
Finished NVD CVE Analyzer (0 seconds)
Finished Sonatype OSS Index Analyzer (0 seconds)
Finished Vulnerability Suppression Analyzer (0 seconds)
Finished Dependency Bundling Analyzer (0 seconds)
Analysis Complete (2 seconds)
Generating report for project 
```
Are people seeing a specific analyzers time increase?

**Comment by dietzsch** [comment]
From what I have seen in the logs so far it seems that the aggregate is executed on every module, Regarding the question with the versions, it changed with 6.x and is no difference between 6.0.1 and 6.0.2.

**Comment by jeremylong** [comment]
It is wasteful to execute aggregate on every module - the aggregate by itself runs against the child modules. When you run aggregate on each child module you end up getting a report in each modules build directory. If you just are looking for the aggregate report you can run it just on the top level project and get a single report.

**Comment by dietzsch** [comment]
Good point, will change the build file and verify that the results are the same. If so, then this could resolve the issue. :-)

**Comment by dietzsch** [comment]
I changed the build so that meanwhile the timing is much better and so we can close this issue.
