### ISSUE TITLE
Gradle 6.8.1 deprecation warning

### ISSUE THREAD

**Issue by udopt** [jeremylong/dependency-check-gradle#208]
Running the dependencyCheckAnalyze task with Gradle 6.8.1 yields the following deprecation warning:

> The archives configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the compileClasspath or runtimeClasspath configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.8.1/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations

I have seen https://github.com/jeremylong/dependency-check-gradle/issues/176, though the message looks different.

**Comment by jeremylong** [comment]
We accept PRs...

**Comment by britter** [comment]
This looks like https://github.com/jeremylong/DependencyCheck/issues/2644.

**Comment by udopt** [comment]
Indeed.
