### ISSUE TITLE
Unable to skip dependencyCheck task programatically

### ISSUE THREAD

**Issue by adolfogarci** [jeremylong/dependency-check-gradle#26]
Plugin adds dependencyCheck task as a dependency on check task. I don't want to execute the analysis on every single build and I would like to execute it only when invoking the task on purpose. 

While performing "gradle build -x dependencyCheck" works perfectly neither of these two options work:
- check.dependsOn.remove('dependencyCheck') -> It actually does nothing
- enabled = false within dependencyCheck config (or dependencyCheck.enabled = false) -> Returns error "No such property: enabled for class: org.owasp.dependencycheck.gradle.extension.CheckExtension_Decorated"

**Comment by m-at-nu** [comment]
Same problem over here.
We decided to switch to version 1.4.3 instead as it doesn't seem to bind automatically to check task and thus doesn't execute on each build.

**Comment by jeremylong** [comment]
I will put a point release out this weekend to address this. Question for
those affected:

Is it better to automatically bind to check and provide an option to skip?
Or would the preference be to not automatically bind?

Jeremy

**Comment by stefanneuhaus** [comment]
@adolfogarci @m-at-nu I had to solve the same issue. You should try it this way:
```check.dependsOn -= tasks['dependencyCheck']```

@jeremylong My preferred behavior would be:
* Default is not to bind to check: As a developer I want to just build fast and do this in a convenient way (no opt-out required). Enabling this for CI server builds does not need to be convenient.
* No configuration option: As the default should be not to bind, opting in via dependsOn is a one-liner, as is applying the configuration setting. Wiring tasks dependencies should be no big deal for any developer that messes around with the build. I personally rather like to have the tool less complex.

**Comment by m-at-nu** [comment]
@stefanneuhaus Thanks for the correct syntax. Removing the task is of course more elegant than using an older version

@jeremylong I totally agree with @stefanneuhaus, default should be not to bind.
In addition to his motivation: changes to dependencies rarely happen and thus re-evaluating them is not necessary for each build. Consequently, an extra job in a CI running an additional command on e.g. a regular basis is probably the desired behavior.

**Comment by adolfogarci** [comment]
@stefanneuhaus Thanks, it worked like a charm 👍 

@jeremylong I agree with @stefanneuhaus and @m-at-nu

**Comment by jeremylong** [comment]
1.4.4.1 was just pushed and removes the automatic binding.
