### ISSUE TITLE
Support for hosted maven repositories and jCenter

### ISSUE THREAD

**Issue by emartynov** [jeremylong/dependency-check-gradle#27]
I see in logs:
```
...
Unable to download pom.xml for javax.inject-1.jar from Central; this could result in undetected CPE/CVEs.
Unable to download pom.xml for equalsverifier-2.1.7.jar from Central; this could result in undetected CPE/CVEs.
...
```

That is might be related that we use own hosted maven repo, or that some dependencies are only distributed through jCenter.

Can I troubleshoot this situation with any setting? Or I should use plugin from sources and modify it?

**Comment by jeremylong** [comment]
Dependency-check attempts to pull down more information about the JAR files it is scanning - specifically, in the case of Central and Nexus analyzers a POM file is retrieved if one is not already contained within the JAR. This is done by using the query functions within Central and Nexus to identify an artifact's coordinates by SHA1 hash. If JCenter, or whatever other repository you are using, has the capability to identify a library by hash and in turn be able to pull back the GAV coordinates one would use to include the dependency in an application then it would be fairly simple to create a new analyzer. Take a look at the [NexusAnalyzer](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/java/org/owasp/dependencycheck/analyzer/NexusAnalyzer.java) as an example.

For more information on why this is done see [this article](http://jeremylong.github.io/DependencyCheck/data/index.html) and of course the [How it works](http://jeremylong.github.io/DependencyCheck/general/internals.html) article if you haven't read it.

Does that help?
