### ISSUE TITLE
Add version of https://nvd.nist.gov/ to report

### ISSUE THREAD

**Issue by emartynov** [jeremylong/dependency-check-gradle#28]
From the report, it is hard to guess which version of https://nvd.nist.gov/ is used.

I'm not familiar with this database but I see they have at least date when database was updated.

Can we include it?

**Comment by jeremylong** [comment]
If you look at the [sample report](http://jeremylong.github.io/DependencyCheck/general/SampleReport.html), at the top you'll see a `Scan Information (show more)` section. Click the show more link and it will expand to include a line that states:

```
NVD CVE Modified: 09/10/2016 06:04:43
```

While there are other NVD CVE dates listed - the only one that matters is the modified date. Basically, dependency-check downloads all of the CVE data from the [NVD Data Feeds](https://nvd.nist.gov/download.cfm) - the first time it runs it downloads everything. After the first run, if you update at least once every 7 days only the `modified` file is downloaded as that contains all of the changes to any of the other files.

**Comment by emartynov** [comment]
Found it! Thank you!

**Comment by jeremylong** [comment]
I don't believe that is the exact date as displayed by the NVD - however, it is the date when the data was downloaded.

**Comment by emartynov** [comment]
Should I reopen ticket?

**Comment by jeremylong** [comment]
It is working as *I* intended; dependency-check is not actually using the
last modified dates from the NVD XML Meta data. Instead, it is using the
last modified HTTP Header. I don't believe this needs to be changed. I was
more posting my above comment to add clarity as to why the dates may not
match exactly.  For files other then the modified XML, the dates may not
actually change over time as we are not pulling those files - we are only
pulling the last modified and updating the necessary data. So the data for
the given years is up-to-date, but the XML files for that year may not have
been downloaded for quite some time.

**Comment by emartynov** [comment]
Do you think it is valueable to see dates for updates, not for dates for download time?

**Comment by jeremylong** [comment]
I think it is fine the way it working.
