### ISSUE TITLE
Add configuration options

### ISSUE THREAD

**Issue by jeremylong** [jeremylong/dependency-check-gradle#29]
Update configuration per https://github.com/jeremylong/DependencyCheck/pull/635 to expose the additional settings.

**Comment by hypery2k** [comment]
would be possible to add an option to skip compile-only deps to?

**Comment by jeremylong** [comment]
I have validated that all file type analyzers are configurable within the gradle plugin.

@hypery2k in the HTML report you will find a line for each dependency that states: 

>`Referenced In Project/Scope: compile, runtime`

You can copy any of the scopes into the configuration:

```groovy
dependencyCheck {
    skipConfigurations=['compile']
    format='ALL'
}
```

**Comment by hypery2k** [comment]
thanks, good to know
