### ISSUE TITLE
Unable to set custom option

### ISSUE THREAD

**Issue by vraravam** [jeremylong/dependency-check-gradle#3]
I'm using the latest version (1.3.3) of this gradle plugin. But, if I try to set the cveValidForHours as documented [here](https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html), I get the following error:
```
Could not find property 'CVE_CHECK_VALID_FOR_HOURS' on task ':dependencyCheck'.
```

The reason I am trying to set this value to something greater than the default is since we are trying to reduce our build times, and this seems like a low hanging fruit with high ROI in our usecase.

**Comment by jeremylong** [comment]
Sorry about this. I was able to replicate the behavior using the currently published plugin. Apparently I have already fixed this bug in the code base as the current snapshot works without any changes. I will push a release within the next day or two.

**Comment by PhilHoff84** [comment]
@jeremylong Using the latest version (currently 1.3.6) I am experiencing the very same issue again.
The [Update.groovy] (https://github.com/jeremylong/dependency-check-gradle/blob/master/src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Update.groovy#L106) file is using `CVE_CHECK_VALID_FOR_HOURS` but lacks the static import from `org.owasp.dependencycheck.utils.Settings`.
Would you mind having a look at this issue?

**Comment by jeremylong** [comment]
Thanks for pointing that out. I'll update my release testing to ensure this get tested correctly prior to the next release (which should be soon).
