### ISSUE TITLE
Report for NPM Packages not generating

### ISSUE THREAD

**Issue by mkornipati** [jeremylong/dependency-check-gradle#35]
@jeremylong, I like this tool a lot and working great! Thanks for the tool and the gradle plugin.

It has been working well for gradle dependencies.  I am referring to https://jeremylong.github.io/DependencyCheck/analyzers/nodejs.html and would like to use this plugin for NPM package scan too and trying with provided extensions and came across this

https://github.com/jeremylong/dependency-check-gradle/blob/master/src/main/groovy/org/owasp/dependencycheck/gradle/extension/AnalyzerExtension.groovy#L119
https://github.com/jeremylong/dependency-check-gradle/blob/master/src/main/groovy/org/owasp/dependencycheck/gradle/extension/AnalyzerExtension.groovy#L29

and trying out passing analyzerExtension  with `nodeEnable=true` and `experimentalEnabled:true` but still seems to be not generating the report for npm packages.

Am I missing anything?

**Comment by jeremylong** [comment]
The gradle plugin only scans dependencies defined within the gradle build.  If you want to scan a node project you would likely need need to use the [command line version of dependency-check](http://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html).

However, for node projects I would recommend looking at the [node security project](https://nodesecurity.io/opensource) and [retire.js](https://retirejs.github.io/retire.js/).

Let me know if this issue can be closed or if you have any other questions or issues.

**Comment by mkornipati** [comment]
Thanks @jeremylong for the confirmation. The provided extensions made me feel, this gradle plugin does support. I will give a try with CLI, NSP or retire.js

Yes, we can close this issue.
