### ISSUE TITLE
plugins.gradle.org does not link to this github repo

### ISSUE THREAD

**Issue by johnscancella** [jeremylong/dependency-check-gradle#36]
If you look on the plugins.gradle.org website for this plugin (https://plugins.gradle.org/plugin/org.owasp.dependencycheck) when you try to click on the link that should take you to the github repo it does not. It instead takes you to https://plugins.gradle.org/plugin/git@github.com:jeremylong/dependency-check-gradle.git

**Comment by jeremylong** [comment]
Thanks for reporting this. The fix will be included in the next release.
