### ISSUE TITLE
Subprojects are reported to the same file, effectively having the last result only

### ISSUE THREAD

**Issue by v6ak** [jeremylong/dependency-check-gradle#5]
Steps to reproduce: Run it on a project with subprojects.

Expected results: Reports for various projects are stored to different files.

Actual results: Reports are written to the same file. As a results, all reports except the last one are overwritten by some other report.

ODC version: 1.3.6

Workarounds: See #1 . Note that the name of the option has been slightly changed to `outputDirectory`.

**Comment by jeremylong** [comment]
Thanks for pointing the issue out! The reports are now stored in the `${project.buildDir}/reports` for each sub-project.

--Jeremy
