### ISSUE TITLE
Need more control over analysed configuration

### ISSUE THREAD

**Issue by bodewig** [jeremylong/dependency-check-gradle#6]
There are a lot of plugins that create their own configurations which end up only being used at build time and don't contribute to the final product, examples are checkstyle or findbugs. These configurations pull in the plugins' dependencies and I'm not really interested in them.

I think it would be good to have more control over the configurations that are analysed, something that generalizes `skipTestGroups`. A white/blacklist of configurations to analyse/skip wouldn't be too hard to implement and I'd be happy to provide a PR. Would you prefer white- or blacklists or even both but making the settings mutually exclusive?

**Comment by jeremylong** [comment]
Probably a mutually exclusive white-list or blacklist would be best.

**Comment by bodewig** [comment]
Thanks, I'll try to come up with a PR by the next weekend.
