### ISSUE TITLE
dependencyCheckAnalyze: Cannot invoke method addProjectReference() on null object

### ISSUE THREAD

**Issue by glever** [jeremylong/dependency-check-gradle#62]
I have a multi-module gradle build where this issue appears since version 2.1.x. With 2.0.1 it still works.
logging output of gradle dependencyCheckAnalyze --info or --debug doesnt really seem helpful, but I'll provide it upon your request.

I created a branch with the failing project configuration:
[https://github.com/glever/xmlers/tree/owasp-dependencyCheck-gradle-error](https://github.com/glever/xmlers/tree/owasp-dependencyCheck-gradle-error)
Issue occurs on modules with references to other project modules. For example in above project from /domain/build.gradle to module :xml . Module xml has no references to other project modules and 'dependencyCheckAnalyze'  works fine.

Seems to be related to Analyze.groovy:60-61 :)
`                
//TODO determine why deps could be null in some cases.
                addInfoToDependencies(deps, artifact, configuration.name)
`

ps: This is an excellent project, thank you very much for your effort.

**Comment by jeremylong** [comment]
Thanks for the bug report - I'm in the middle of some research for an upcoming talk so it might take me a few weeks to really dig into this problem.

**Comment by jeremylong** [comment]
Sorry about the **massive** delay in response on this ticket.  I finally got back to testing this and it appears to be resolved.  I made some minor changes to your `build.gradle` (see below) and running the aggregate task worked: `gradle dependencyCheckAggregate`


```diff
diff --git a/build.gradle b/build.gradle
index 41d2e8f..f8a36af 100644
--- a/build.gradle
+++ b/build.gradle
@@ -1,12 +1,13 @@
 buildscript {
 	repositories {
+		mavenLocal()
 		mavenCentral()
 	}
 	ext.jaxb_version = '2.3.0'
 	ext.kotlin_version = '1.1.51'
 
 	dependencies {
-		classpath 'org.owasp:dependency-check-gradle:3.0.1'
+		classpath 'org.owasp:dependency-check-gradle:3.1.2'
 	}
 }
 
@@ -17,6 +18,10 @@ plugins {
 	id "org.jetbrains.kotlin.plugin.spring" version "1.1.51"
 }
 
+repositories {
+	mavenCentral()
+	mavenLocal()
+}
 
 defaultTasks 'xjc','build'
 
@@ -81,7 +86,7 @@ subprojects {
 	tasks.withType(JavaCompile) { options.encoding = 'UTF-8' }
 
 	repositories {
-		maven { url "http://repo.maven.apache.org/maven2"}
+		mavenCentral()
 		mavenLocal()
 	}
 
```

**Comment by jeremylong** [comment]
Note - with the above changes to the `build.gradle` I was also able to succesfully execute:

```
gradle xjc build dependencyCheckAnalyze
```

**Comment by jeremylong** [comment]
I apologize that this has taken me so long to get back to - however, a patch will be included in the next release. See PR #88.
