### ISSUE TITLE
Default suppressions

### ISSUE THREAD

**Issue by alinbutura** [jeremylong/dependency-check-gradle#68]
Hi Jeremy,

Could you tell me if the default suppressions defined here https://github.com/jeremylong/DependencyCheck/blob/60fd4f6311e1febf9b4e019f65fc0e8ef5e9897b/dependency-check-core/src/main/resources/dependencycheck-base-suppression.xml are used by the dependency check CLI?

Thanks a lot,
Alin

**Comment by jeremylong** [comment]
Yes, those are the base list of known FP that dependency-check identifies.

**Comment by alinbutura** [comment]
Ok, great. Thanks! Case closed.
