### ISSUE TITLE
dependencyCheckAnalyze fails in Android project with more than one modules

### ISSUE THREAD

**Issue by gmetal** [jeremylong/dependency-check-gradle#71]
After updating an Android application to Gradle 4.1, the dependencyCheckAnalyze task has started failing. It appears that it is unable to handle multiple modules. I have created a sample  app that demonstrates the problem: https://github.com/gmetal/sample-dependency-check-app
If you run the dependencyCheckAnalyze task, you'll see something like the following:
```
./gradlew dependencyCheckAnalyze

> Task :app:dependencyCheckAnalyze
Verifying dependencies for project app


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dependencyCheckAnalyze'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > More than one variant of project :mylibrary matches the consumer attributes:
       - Configuration ':mylibrary:debugApiElements' variant android-aidl:
           - Found artifactType 'android-aidl' but wasn't required.
           - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.
       - Configuration ':mylibrary:debugApiElements' variant android-classes:
           - Found artifactType 'android-classes' but wasn't required.
           - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.
       - Configuration ':mylibrary:debugApiElements' variant android-manifest:
           - Found artifactType 'android-manifest' but wasn't required.
           - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.
       - Configuration ':mylibrary:debugApiElements' variant android-renderscript:
           - Found artifactType 'android-renderscript' but wasn't required.
           - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.
       - Configuration ':mylibrary:debugApiElements' variant jar:
           - Found artifactType 'jar' but wasn't required.
           - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

**Comment by jeremylong** [comment]
Thanks for the bug report. I will try to look at this in the next two weeks.

**Comment by DeychAI** [comment]
Any updates?

**Comment by mauricegavin** [comment]
We're also facing this issue. Is there anything we can do to help?

**Comment by adjorno** [comment]
Hope it will be fixed soon.

**Comment by andyhermann** [comment]
My workaround for this issue:
- when defining the module depdendency add a configuration
`
`

**Comment by jeremylong** [comment]
All - I'm still researching this. Unfortunately, I am not seeing a quick fix.

**Comment by jeremylong** [comment]
I've looked at several other plugins that deal with project dependencies and I have not yet found a solution.  Most other plugins obtain the `ResolvedDependency` objects which works if you are just gathering the coordinates of the dependency; however, dependency-check uses the actual JAR file. When attempting to obtain the `ResolvedArtifact` objects is where the error occurs.  I have asked a [question on SO](https://stackoverflow.com/questions/51231805/gradle-plugin-getartifacts-results-in-could-not-resolve-all-dependencies-fo) and will likely be following up with gradle support shortly.

**Comment by jeremylong** [comment]
I just found the solution to the problem.  See https://stackoverflow.com/a/44207419/1995422

In the sample project's [app/gradle.build#L24](https://github.com/gmetal/sample-dependency-check-app/blob/ecd85a0d72c552b3c55822179c145ee1ac5a857e/app/build.gradle#L24) change

```groovy
implementation project(':mylibrary')
```
To 
```groovy
implementation project(path: ':mylibrary', configuration: 'default')
```

Explicitly setting the configuration on the project reference resolves the error.  Additional enhancements are being made to better support Android AAR dependencies.

**Comment by jeremylong** [comment]
I should point out that the solution to this (which I outlined above) was previously provided https://github.com/jeremylong/dependency-check-gradle/issues/71#issuecomment-367931630 - I wanted to exhaust some avenues of research before finalizing this as the best answer.  I believe there might be an underlying issue between gradle and the android sdk that causes this problem as @andyhermann pointed out - this does cause an issue in android studio.

**Comment by jeremylong** [comment]
I did open a ticket with gradle (https://github.com/gradle/gradle/issues/5953) to see if they believe there is an underlying issue.

**Comment by gmetal** [comment]
I had a quick look at the change your are proposing. It seems to resolve the errors you get when running the dependencyCheckAnalyze. However, as others have pointed out, if you attempt to sync the project in Android Studio (used 3.2-beta3), it fails. 

On the sample project though, simply building the application (e.g. ```./gradlew assembleDebug```) on the project root folder once, allows AS to figure out what it is missing and sync the project. I even managed to build the APK and run it in a real device. 

After trying the same workaround in a more complex project with multiple modules, and many dependencies, I could not get the ```./gradlew assembleFlavourDebug``` step to complete properly.

**Comment by jeremylong** [comment]
The ticket with the gradle team pointed me in a different direction (see https://github.com/gradle/gradle/issues/5953#issuecomment-404514591). I am still trying to fully understand some of the new/incubating APIs but hope to have something soon.
