### ISSUE TITLE
Can we add a disable all checks setting?

### ISSUE THREAD

**Issue by spyhunter99** [jeremylong/dependency-check-gradle#72]
Would it be possible to add a configuration setting for the analyze task to skip all processing?

Context: In [gradle-fury](https://github.com/gradle-fury/gradle-fury) we have build profiles similar to maven profiles that we can enable/disable from the command line. If addition, the build script checks a properties file for a set to properties to conditionally enable/disable certain checks, pmd, checkstyle, etc, include the dependency check. There is no way in gradle (that i've discovered) to conditionally "apply" a plugin, therefore the plugin has to have an enabled/disabled property that can be set.

**Comment by jeremylong** [comment]
The `skip` configuration was added to maven plugin - but I forgot to add it to the gradle task. I will hopefully be releasing a new version shortly that will include this. You will be able to configure:
```groovy
dependencyCheck {
  skip = true
}
```

Will that work?

**Comment by spyhunter99** [comment]
that would be perfect!

**Comment by spyhunter99** [comment]
any updates on this?

**Comment by jeremylong** [comment]
I apologize - the last release was done in haste (3.1.2) with really bad internet while I was on vacation...   I apparently forgot to update this tickets in the gradle repo.  This was included in 3.1.2 - please see the `skip` option which is now available in the configuration: https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html
