### ISSUE TITLE
dependencyCheckAnalyze Fails Due to Ruby Bundle Audit Analyzer

### ISSUE THREAD

**Issue by EarthCitizen** [jeremylong/dependency-check-gradle#73]
Plugin version 3.0.2. Getting this exception, which causes dependencyCheckAnalyze to fail:

> Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
>   Exception from bundle-audit process: java.io.IOException: Cannot run program "bundle-audit" (in directory "/tmp/dctempfb15b599-7ed4-4371-8936-fb14f05dc4ba"): error=2, No such file or directory. Disabling Ruby Bundle Audit Analyzer
>   at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:693)
>   at org.owasp.dependencycheck.Engine$analyzeDependencies$0.call(Unknown Source)
>   at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:76)

Workaround:

```
dependencyCheck {
  analyzers {
    bundleAuditEnabled = false
  }
}
```

**Comment by jeremylong** [comment]
With regard to Ruby dependencies - dependency-check is currently only wrapping [bundle-audit](https://github.com/rubysec/bundler-audit). If you are working with Ruby dependencies I would highly recommend installing `bundle-audit`.

**Comment by EarthCitizen** [comment]
Would it be better if bundle-audit is automatically disabled if not on PATH?
