### ISSUE TITLE
Tag v3.1.1 is a snapshot linking to ODC 3.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by v6ak** [jeremylong/dependency-check-gradle#75]
Tag v3.1.1 is wrong or maybe I don't understand the tagging scheme.

I would assume that:

* Version tag contains a release, not a snapshot.
* Versioning scheme tries to be on par with ODC core (with possible fix versions), so version 3.1.1 (and possibly also fix versions like 3.1.1.1, 3.1.1.2, 3.1.1.3 etc.) use ODC 3.1.1.
* Release versions link to stable (immutable*) versions, not snapshots.

Tag v3.1.1 breaks the first two assumptions. (By definition, the third assumption cannot be broken by snapshots.) So, I'd like to ask if my assumptions are wrong or the tag is wrong.

* Version tag v3.1.1 links to version v3.1.1-SNAPSHOT.
* The version uses ODC core 3.1.0-SNAPSHOT, so bare version of Gradle plugin does not match the used version of ODC.

EDIT: Moreover, the [version 3.1.1 seems to be released](https://mvnrepository.com/artifact/org.owasp/dependency-check-gradle/3.1.1), despite it is not present in the Git repository.

---
 
\*) Snapshot versions are mutable, while standard releases (including alphas, betas, RCs, M*s etc) should be immutable. My point is rather about immutability (i.e., you use a version that does not change) than about maturity of the versions.

**Comment by jeremylong** [comment]
I missed a single commit prior to tagging v3.1.1 - this does not affect the actual release of 3.1.1 in anyway. I have fixed the v3.1.1 tag and it represents what was previously published to the plugin portal.
