### ISSUE TITLE
Having to apply the "java" plugin to allprojects

### ISSUE THREAD

**Issue by troessner** [jeremylong/dependency-check-gradle#85]
We have the following set up straight out of the README for our multi-module project:

```Groovy
allprojects {
  apply plugin: 'ca.cutterslade.analyze'
}
subprojects {
  apply plugin: 'java'
}
```

Which failed with: 

```
 gradle analyzeClassesDependencies
Starting a Gradle Daemon, 1 busy and 6 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Task 'analyzeClassesDependencies' not found in root project 'xyz'.
```

We had to change our set up to this:

```Groovy
allprojects {
    apply plugin: 'java'
    apply plugin: 'ca.cutterslade.analyze'
}

subprojects {
  // completely empty now
}
```

Is this some glitch in the documentation?

**Comment by jeremylong** [comment]
This does not look like an OWASP dependency-check issue?  Did you mean to submit this issue to https://github.com/wfhartford/gradle-dependency-analyze?

**Comment by troessner** [comment]
>> Did you mean to submit this issue to https://github.com/wfhartford/gradle-dependency-analyze?

Oh yeah, my bad, sorry!
