### ISSUE TITLE
Always showing 0 depencies in an android project

### ISSUE THREAD

**Issue by thelittlefireman** [jeremylong/dependency-check-gradle#86]
Hi ,
I try to run it under an android project but it always showing 0 Dependencies : 

> Dependencies Scanned: 0 (0 unique)

it's an android project under gradle 3.5.1 and android.plugin : 2.3.3

thanks

**Comment by thelittlefireman** [comment]
it's seem that you are not using the same methode to resolve depency as this plugin : https://github.com/ben-manes/gradle-versions-plugin which check if a newer version of the dependency is available.

if it can help ==> https://github.com/ben-manes/gradle-versions-plugin/blob/6b0425076c061642dc0b16a33abe114a3ce06bf0/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy#L104

**Comment by thelittlefireman** [comment]
For more informations it works with android.plugin.gradle 3.1.3 and gradle 4.8

**Comment by jeremylong** [comment]
Interesting - so upgrading to the latest android plugin and gradle version resolve the issue?  Looking at the errors it seemed like there might have been a bug between the android plugin and gradle.

Can this issue be closed then?

**Comment by jeremylong** [comment]
With the updates to artifact resolution made to support #71 (see PR #90) I am going to close this issue.
