### ISSUE TITLE
dependencyCheckAggregate does not aggregate reports

### ISSUE THREAD

**Issue by mayur9991** [jeremylong/dependency-check-gradle#93]
Hello,

We have a multi module gradle project and I am trying to generate an aggregated report using dependencyCheckAggregate task.

```
subprojects {
    apply plugin: 'org.owasp.dependencycheck'

    dependencyCheck {
        format = 'HTML'
    }
}
```

I have above subprojects configuration but it is generating report in each subproject build directory instead of creating a one in root directory.

**Comment by yunj** [comment]
Hi,

As described in https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration-aggregate.html, you just need to add the root project level.

**Comment by mayur9991** [comment]
Thanks 👍
