### ISSUE TITLE
release 3.3.X breaks support for gradle < v4.0

### ISSUE THREAD

**Issue by milo-minderbinder** [jeremylong/dependency-check-gradle#95]
Obviously since Gradle 3.3 was released in Jan 2017, that may not be a huge issue **[1]**, but it might be worth documenting so that users aren't confused when updating the plugin version breaks their build. As far as I can tell from a quick glance, the breaking change was [here](https://github.com/jeremylong/dependency-check-gradle/commit/4f487a3936f52c7c0b84ae457ab25cb87fffd671#diff-f54dbc129151158e6d7a39138a0a7eceR27) due to use of the `org.gradle.api.attributes.Attribute` class, which was introduced in [Gradle version 3.3](https://docs.gradle.org/current/javadoc/org/gradle/api/attributes/Attribute.html)

**[1]**: YMMV, but in my experience, _way_ too many projects rarely, if ever, update their gradle wrapper unless something breaks, so I still see Gradle 2.X quite often.

**Comment by jeremylong** [comment]
It looks like the current minimum version of gradle for dependency-check-gradle 3.3.x is 4.0.  I'm debating putting the older dependency resolution back in and use it when the gradle version is less then 4.0 or just saying the minimum gradle version is 4.0.
