### ISSUE TITLE
How to exclude sub project when running dependencyCheckAggregate

### ISSUE THREAD

**Issue by jrodguitar** [jeremylong/dependency-check-gradle#99]
Hello,

i have been using this plugin, and it is working great, but i cannot exclude sub projects when running dependencyCheckAggregate.
if i do
dependencyCheck{
 skip = true
}
in one sub project, it skips the entire scan.

any advise? thanks in advance.

**Comment by jeremylong** [comment]
Unfortunately, with the aggregate goal there is no way to skip a child-project. I'll put this on the list of future enhancements.

**Comment by yunj** [comment]
Hi @jrodguitar the latest M2 has the ability to exclude subprojects. What you need to do is to pass a list of subprojects’ paths to skipProjects. Please give it a try to see if it could meet your needs. Cheers

**Comment by jrodguitar** [comment]
@yunj  Thanks i will try it.
